# Generated by Django 4.0.5 on 2022-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='changeName',
            field=models.CharField(default='lost Name', max_length=100),
        ),
    ]
